### ISSUE TITLE
Sign-up module

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#11] opened 2017-03-15 10:57 UTC
As a user, I want to be able to sign up quickly and easily

This is currently
-name
-email address
-phone number

There were questions in the kick-off meeting about password generation and also whether or not all fields were compulsory (some users may not want to give their phone number)

![screen shot 2017-03-15 at 10 56 36](https://cloud.githubusercontent.com/assets/26304634/23945353/2101556e-096e-11e7-98aa-faa5f473e0ee.png)

**Comment by sarahwelton** [comment] 2017-03-15 14:12
As discussed in our meeting today, we still need clarification on the password generation. 

Also, the team at RR are putting together form fields which they will share with us, so these may be subject to change. Eg, first name, last name, email address, password. Phone number may or may not be required. Will confirm asap.

**Comment by SimonLab** [comment] 2017-03-15 15:12
To start on the signup process we were planning to create a form with
- email
- password
- phone

From the redcap database it seems that the profile of the user will have first name and last name so at the moment it will be difficult to extract this information from just the name field on the form that's why for the first step we think to exclude this form on the website.
 The signup login form can be updated later on with new fields but we think the email, password and phone are a good way to start on this and to let the users access the first consent page
@ellemindwave @sarahwelton does this sounds good?
![login-ttrr](https://cloud.githubusercontent.com/assets/6057298/23956588/f3f6dce8-0994-11e7-9fd4-17f44e478122.png)

**Comment by SimonLab** [comment] 2017-03-15 15:55
Sorry @sarahwelton I just read again your previous text and we can definitely add  first name, last name, email address, password

**Comment by Danwhy** [comment] 2017-03-16 10:13
We'll need to reuse the signup form on multiple pages.
Reusing Phoenix components: http://blog.danielberkompas.com/2017/01/17/reusable-templates-in-phoenix.html

**Comment by ellemindwave** [comment] 2017-03-17 12:04
@SimonLab @Danwhy How do we test this / see it? Is there a link?

**Comment by ellemindwave** [comment] 2017-03-17 14:30
@Danwhy @SimonLab I get this error message when trying to sign up:

![screen shot 2017-03-17 at 14 28 48](https://cloud.githubusercontent.com/assets/26304634/24047630/34736ed2-0b1e-11e7-8d6d-35864a295bb3.png)

**Comment by SimonLab** [comment] 2017-03-17 14:46
Thanks for testing that @ellemindwave , it should be ok now.

**Comment by ellemindwave** [comment] 2017-03-17 15:48
Thanks @SimonLab It seems to be working correctly now 👍

**Comment by ghost** [comment] 2017-03-24 11:00
Sign up worked for me, but I did get the above error page when entering details I had already signed up with - should this be raised as a separate issue @Cleop and this one closed?

@sarahwelton is it confirmed that you don't need phone number yet?

**Comment by Cleop** [comment] 2017-03-24 12:26
Thanks @katyedwards I'll raise it as a separate issue re duplicate sign up errors. Please close this if you're happy to.

**Comment by Cleop** [comment] 2017-03-24 12:29
Looks like it's already been created as a new issue: #73

**Comment by ghost** [comment] 2017-03-24 12:33
Yes sorry - I thought I'd created a new issue (before I'd looked at this one) but couldn't find it so assumed I hadn't 'saved' it - then Kat noticed I'd somehow managed to put it in HL - goodness knows how!  Thanks!

**Closed as completed by ghost** 2017-03-24 12:33 UTC
Labels: question, please-test, T1d
